# Generated by Django 5.2.6 on 2025-09-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinarycase',
            name='case_type',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='disciplinarycase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='disciplinarycase',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='disciplinarycase',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('hearing', 'Hearing Scheduled'), ('resolved', 'Resolved'), ('appealed', 'Appealed'), ('closed', 'Closed')], db_index=True, default='reported', max_length=20),
        ),
    ]
