# Generated by Django 5.2.6 on 2025-09-25 11:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinary', '0002_alter_disciplinarycase_case_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='DisciplinaryNotification',
        ),
    ]
