# Generated by Django 5.2.6 on 2025-09-26 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('finance', 'Finance'), ('units', 'Units'), ('exams', 'Exams'), ('assignments', 'Assignments'), ('timetable', 'Timetable'), ('hostel', 'Hostel'), ('clearance', 'Clearance'), ('graduation', 'Graduation'), ('general', 'General')], max_length=32)),
                ('type', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('urgency', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('urgent', 'Urgent')], default='info', max_length=16)),
                ('channels', models.JSONField(default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_links', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='en', max_length=8)),
                ('personalized_context', models.JSONField(blank=True, default=dict)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=32)),
                ('requires_ack', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('escalation_sent', models.BooleanField(default=False)),
                ('escalation_at', models.DateTimeField(blank=True, null=True)),
                ('offline_queued', models.BooleanField(default=False)),
                ('offline_synced', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NotificationActionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=255)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('ignored', models.BooleanField(default=False)),
                ('ignored_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=16)),
                ('status', models.CharField(max_length=32)),
                ('attempt', models.IntegerField(default=1)),
                ('response', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('users', models.ManyToManyField(related_name='notification_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('language', models.CharField(default='en', max_length=8)),
                ('receive_urgent_sms', models.BooleanField(default=True)),
                ('receive_push', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='notifications.notification')),
            ],
        ),
    ]
