# Generated by Django 5.2.6 on 2025-09-25 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=16)),
                ('exam_type', models.CharField(choices=[('ordinary', 'Ordinary'), ('special', 'Special'), ('supplementary', 'Supplementary'), ('retake', 'Retake')], max_length=16)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='exam_cards/qrcodes/')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='exam_cards/barcodes/')),
                ('download_history', models.JSONField(blank=True, default=list)),
                ('approved_by_registrar', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
