# Generated by Django 5.2.6 on 2025-09-25 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_card', '0001_initial'),
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('generated', 'Generated'), ('downloaded', 'Downloaded'), ('verified', 'Verified'), ('blocked', 'Blocked'), ('unblocked', 'Unblocked'), ('override', 'Override')], max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='exam_card.examcard')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_profile.studentprofile')),
            ],
        ),
    ]
