# Generated by Django 5.2.6 on 2025-09-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_card', '0002_examcardevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcard',
            name='exam_schedule',
            field=models.JSONField(blank=True, default=list, help_text='Exam schedule for this card'),
        ),
        migrations.AddField(
            model_name='examcard',
            name='failed_units',
            field=models.JSONField(blank=True, default=list, help_text='List of failed units for supplementary card'),
        ),
        migrations.AddField(
            model_name='examcard',
            name='finance_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examcard',
            name='history',
            field=models.JSONField(blank=True, default=list, help_text='Tracking and history for special exam approvals'),
        ),
        migrations.AddField(
            model_name='examcard',
            name='reprint_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examcard',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Supporting document for special exam card', null=True, upload_to='exam_cards/supporting_docs/'),
        ),
    ]
