# Generated by Django 5.2.6 on 2025-09-25 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancedocument',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clearance.clearancedepartment'),
        ),
        migrations.AddField(
            model_name='clearancedocument',
            name='soft_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='is_disciplinary_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='is_fees_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='is_hostel_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='is_library_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='is_other_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='soft_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ClearanceAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='clearance.clearancerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clearance.clearanceapproval')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceDigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_file', models.FileField(blank=True, null=True, upload_to='clearance_signatures/%Y/%m/%d/')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signature', to='clearance.clearanceapproval')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(default='system', max_length=32)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clearance.clearancerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='clearance.clearancerequest')),
            ],
        ),
    ]
