# Generated by Django 5.2.6 on 2025-09-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('tuition', 'Tuition Fees'), ('accommodation', 'Accommodation/Hostel Fees'), ('registration', 'Registration/Admission Fees'), ('library', 'Library Fees'), ('examination', 'Examination Fees'), ('graduation', 'Graduation Fees'), ('medical', 'Medical/Insurance Fees'), ('activity', 'Activity Fees'), ('technology', 'Technology/ICT Fees'), ('penalty', 'Penalty/Disciplinary Fees'), ('other', 'Other Services')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
