# Generated by Django 5.2.6 on 2025-09-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_non_refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='is_non_refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='minimum_percentage_required',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
