# Generated by Django 5.2.6 on 2025-09-25 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_virus_free',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='attachments.attachment'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='version',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='attachment',
            name='virus_scan_report',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AttachmentNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='attachments.attachment')),
            ],
        ),
    ]
