# Generated by Django 5.2.6 on 2025-09-25 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_attachmentcomment_delete_attachmentaudit'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='download_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='expiry_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_preview',
            field=models.FileField(blank=True, null=True, upload_to='attachment_previews/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='attachment',
            name='shared_with_groups',
            field=models.ManyToManyField(blank=True, related_name='group_shared_attachments', to='auth.group'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, related_name='shared_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AttachmentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download')], max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='attachments.attachment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='attachments', to='attachments.attachmenttag'),
        ),
    ]
