# Generated by Django 5.2.6 on 2025-09-25 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_attachmenttag_attachment_download_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentaccesslog',
            name='action',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='attachmentaccesslog',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attachments.attachment'),
        ),
        migrations.AlterField(
            model_name='attachmentaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attachmentcomment',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attachments.attachment'),
        ),
        migrations.AlterField(
            model_name='attachmentcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attachmentnotificationlog',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attachments.attachment'),
        ),
        migrations.AlterField(
            model_name='attachmentnotificationlog',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='attachmentnotificationlog',
            name='recipient',
            field=models.CharField(max_length=128),
        ),
    ]
