# Generated by Django 5.2.6 on 2025-09-28 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_registrar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisabilityCategory',
        ),
        migrations.RemoveField(
            model_name='leaveofabsence',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='leaveofabsence',
            name='student',
        ),
        migrations.RemoveField(
            model_name='registrarauditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registrarprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='study_mode',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='student',
        ),
        migrations.RenameField(
            model_name='disability',
            old_name='description',
            new_name='support_needs',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_number',
        ),
        migrations.RemoveField(
            model_name='studymode',
            name='description',
        ),
        migrations.AddField(
            model_name='disability',
            name='category',
            field=models.CharField(choices=[('physical', 'Physical'), ('visual', 'Visual'), ('hearing', 'Hearing'), ('cognitive', 'Cognitive'), ('other', 'Other')], default='other', max_length=16),
        ),
        migrations.AddField(
            model_name='disability',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disabilities', to='core.studentprofile'),
        ),
        migrations.AddField(
            model_name='disability',
            name='tagged_for_reporting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='disability',
            name='name',
            field=models.CharField(default='General', max_length=32),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_disability', to='core.disability'),
        ),
        migrations.AlterField(
            model_name='studymode',
            name='name',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('distance', 'Distance/Online')], max_length=32, unique=True),
        ),
        migrations.DeleteModel(
            name='GraduationClearance',
        ),
        migrations.DeleteModel(
            name='LeaveOfAbsence',
        ),
        migrations.DeleteModel(
            name='RegistrarAuditLog',
        ),
        migrations.DeleteModel(
            name='RegistrarProfile',
        ),
        migrations.DeleteModel(
            name='StudentAdmission',
        ),
        migrations.DeleteModel(
            name='TransferRequest',
        ),
    ]
