# Generated by Django 5.2.6 on 2025-09-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_disabilitycategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='student', max_length=32),
        ),
    ]
