# Generated by Django 5.2.6 on 2025-09-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Lecturer', 'Lecturer'), ('Finance Staff', 'Finance Staff'), ('Registrar', 'Registrar'), ('System Administrator', 'System Administrator'), ('Parent/Guardian', 'Parent/Guardian'), ('Guest', 'Guest'), ('Support Staff', 'Support Staff')], default=None, max_length=32, null=True, unique=True),
        ),
    ]
