# Generated by Django 5.2.6 on 2025-09-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_role'),
        ('core', '0006_restore_registrarprofile'),
    ]

    operations = [
    ]
