# Generated by Django 5.2.6 on 2025-09-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
